import { kinematicById } from './catalog';
import { fmt, letter, num } from './math';
import { safeHomeX, safeHomeY } from './validators';
import { getMotorReadout } from './transforms';
import type { AppState, KinematicDefinition } from './types';

export function generateConfig(state: AppState): string {
  const kin = kinematicById(state.values.kinematics);
  const sections = [header(kin, state), printerSection(kin, state), stepperSections(kin, state)];
  if (kin.supportsProbeFeatures && state.values.probeFeaturesEnabled) {
    sections.push(probeSections(state), safeZHomeSection(state, kin), bedMeshSection(state));
    if (state.values.screwsEnabled) sections.push(screwsTiltSection(state));
  }
  if (state.values.extruderEnabled) sections.push(extruderSection(state));
  sections.push(summarySection(kin, state));
  return sections.filter(Boolean).join('\n\n');
}

function header(kin: KinematicDefinition, state: AppState): string {
  const v = state.values;
  return [
    '# Klipper positioning configuration',
    '# Generated by Klipper Visual Kinematics',
    `# Kinematics: ${kin.id} (${kin.name})`,
    `# Bed: ${v.bed_x} x ${v.bed_y} mm at X${v.bed_x_offset} Y${v.bed_y_offset}, Z ${v.bed_z} mm`,
    '# Review pins, directions, rotation_distance, and calibration values before use.'
  ].join('\n');
}

function printerSection(kin: KinematicDefinition, state: AppState): string {
  const v = state.values;
  const lines = ['[printer]', `# visual_bed_offset: ${v.bed_x_offset}, ${v.bed_y_offset}`, `kinematics: ${kin.id}`, `max_velocity: ${v.max_velocity}`, `max_accel: ${v.max_accel}`];
  if (hasValue(v.minimum_cruise_ratio)) lines.push(`minimum_cruise_ratio: ${v.minimum_cruise_ratio}`);
  if (kin.id !== 'none') {
    lines.push(`max_z_velocity: ${v.max_z_velocity}`, `max_z_accel: ${v.max_z_accel}`, `square_corner_velocity: ${v.square_corner_velocity}`);
  }
  if (kin.id === 'delta') lines.push(`minimum_z_position: ${v.z_min}`, `delta_radius: ${v.delta_radius}`, `print_radius: ${v.print_radius}`);
  if (kin.id === 'deltesian') lines.push(`minimum_z_position: ${v.z_min}`, `min_angle: ${v.min_angle}`, `print_width: ${v.print_width}`, `slow_ratio: ${v.slow_ratio}`);
  if (kin.id === 'rotary_delta') lines.push(`minimum_z_position: ${v.z_min}`, `shoulder_radius: ${v.shoulder_radius}`, `shoulder_height: ${v.shoulder_height}`);
  if (kin.id === 'polar') lines.push(`max_angular_velocity: ${v.max_angular_velocity}`);
  return lines.join('\n');
}

function stepperSections(kin: KinematicDefinition, state: AppState): string {
  const v = state.values;
  if (kin.id === 'none') return '# No stepper sections are generated for kinematics: none.';
  if (kin.family === 'rectangular') return rectangularSteppers(kin, state);
  if (kin.id === 'delta') {
    return [
      deltaStepper('stepper_a', num(v.tower_a_x), num(v.tower_a_y), v.delta_a_position_endstop, state, true),
      deltaStepper('stepper_b', num(v.tower_b_x), num(v.tower_b_y), v.delta_b_position_endstop, state, false),
      deltaStepper('stepper_c', num(v.tower_c_x), num(v.tower_c_y), v.delta_c_position_endstop, state, false),
      ['[delta_calibrate]', `radius: ${v.delta_calibrate_radius}`, `speed: ${v.delta_calibrate_speed}`, `horizontal_move_z: ${v.delta_horizontal_move_z}`].join('\n')
    ].join('\n\n');
  }
  if (kin.id === 'deltesian') {
    return [
      '[stepper_left]',
      '# Controls the left tower arm.',
      ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(v.default_gear_ratio || '') }),
      `homing_speed: ${v.homing_speed_z}`,
      `second_homing_speed: ${fmt(num(v.homing_speed_z) / 2, 1)}`,
      `arm_length: ${v.arm_length}`,
      `arm_x_length: ${v.arm_x_length}`,
      `position_endstop: ${v.deltesian_left_position_endstop}`,
      `position_min: ${v.z_min}`,
      `position_max: ${v.z_max}`,
      '',
      '[stepper_right]',
      '# Controls the right tower arm.',
      ...commonStepperLines(state, { includeEndstop: true, includeHoming: false, gearRatio: String(v.default_gear_ratio || '') }),
      `arm_length: ${v.arm_length}`,
      `arm_x_length: ${v.arm_x_length}`,
      `position_endstop: ${v.deltesian_right_position_endstop}`,
      '',
      '[stepper_y]',
      '# Controls the independent Y axis.',
      ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(v.default_gear_ratio || '') }),
      `homing_speed: ${v.homing_speed_y}`,
      `second_homing_speed: ${v.second_homing_speed}`,
      `position_endstop: ${v.home_y}`,
      `position_min: ${v.y_min}`,
      `position_max: ${v.y_max}`,
      '',
      '# Deltesian printer-level options',
      '# Deltesian-specific range options are emitted in [printer].'
    ].join('\n');
  }
  if (kin.id === 'rotary_delta') {
    const angles = { a: 30, b: 150, c: 270 };
    return (
      (['a', 'b', 'c'] as const)
        .map((id) =>
          [
            `[stepper_${id}]`,
            '# Rotary delta arm stepper.',
            ...commonStepperLines(state, { includeEndstop: true, includeHoming: id === 'a', omitRotationDistance: true, gearRatio: String(v.rotary_gear_ratio) }),
            ...(id === 'a' ? [`homing_speed: ${v.homing_speed_z}`, `second_homing_speed: ${fmt(num(v.homing_speed_z) / 2, 1)}`] : []),
            `upper_arm_length: ${v.upper_arm_length}`,
            `lower_arm_length: ${v.lower_arm_length}`,
            `position_endstop: ${v[`rotary_${id}_position_endstop`]}`,
            `angle: ${angles[id]}`
          ].join('\n')
        )
        .join('\n\n') +
      '\n\n' +
      ['[delta_calibrate]', `radius: ${v.rotary_delta_calibrate_radius}`, `speed: ${v.rotary_delta_calibrate_speed}`, `horizontal_move_z: ${v.rotary_horizontal_move_z}`].join('\n')
    );
  }
  if (kin.id === 'polar') {
    return [
      '[stepper_bed]',
      '# Controls bed rotation. Klipper requires gear_ratio and no rotation_distance here.',
      ...commonStepperLines(state, { includeEndstop: false, includeHoming: false, omitRotationDistance: true, gearRatio: String(v.bed_gear_ratio) }),
      '',
      '[stepper_arm]',
      '# Controls radial carriage motion.',
      ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(v.arm_gear_ratio) }),
      `homing_speed: ${v.homing_speed_x}`,
      `second_homing_speed: ${v.second_homing_speed}`,
      'position_endstop: 0',
      'position_min: 0',
      `position_max: ${v.polar_radius}`,
      '',
      '[stepper_z]',
      '# Controls Z axis.',
      ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(v.default_gear_ratio || '') }),
      `homing_speed: ${v.homing_speed_z}`,
      `second_homing_speed: ${fmt(num(v.homing_speed_z) / 2, 1)}`,
      `position_endstop: ${v.home_z}`,
      `position_min: ${v.z_min}`,
      `position_max: ${v.z_max}`
    ].join('\n');
  }
  if (kin.id === 'winch') {
    return state.winches
      .map((w, index) =>
        [
          `[stepper_${letter(index)}]`,
          '# Cable winch stepper.',
          ...commonStepperLines(state, { includeEndstop: false, includeHoming: false, omitRotationDistance: true, gearRatio: String(state.values.default_gear_ratio || '') }),
          `rotation_distance: ${w.rotation_distance}`,
          `anchor_x: ${w.x}`,
          `anchor_y: ${w.y}`,
          `anchor_z: ${w.z}`
        ].join('\n')
      )
      .join('\n\n');
  }
  if (kin.id === 'generic_cartesian') return genericCartesianSections(state);
  return '';
}

function rectangularSteppers(kin: KinematicDefinition, state: AppState): string {
  const v = state.values;
  const labelMap: Partial<Record<KinematicDefinition['id'], string[]>> = {
    cartesian: ['X axis', 'Y axis', 'Z axis'],
    corexy: ['X axis / X+Y motor', 'Y axis / X-Y motor', 'Z axis'],
    corexz: ['X axis / X+Z motor', 'Y axis', 'Z axis / X-Z motor'],
    hybrid_corexy: ['X-Y coupled motor', 'Y axis motor', 'Z axis'],
    hybrid_corexz: ['X-Z coupled motor', 'Y axis motor', 'Z axis']
  };
  const labels = labelMap[kin.id] ?? ['X axis', 'Y axis', 'Z axis'];
  return [
    axisStepper('stepper_x', labels[0], v.x_min, v.x_max, v.home_x, v.homing_speed_x, v.second_homing_speed, state),
    axisStepper('stepper_y', labels[1], v.y_min, v.y_max, v.home_y, v.homing_speed_y, v.second_homing_speed, state),
    ['[stepper_z]', `# ${labels[2]}.`, ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(v.default_gear_ratio || '') }), `homing_speed: ${v.homing_speed_z}`, `second_homing_speed: ${fmt(num(v.homing_speed_z) / 2, 1)}`, `position_endstop: ${v.home_z}`, `position_min: ${v.z_min}`, `position_max: ${v.z_max}`].join('\n')
  ].join('\n\n');
}

function axisStepper(section: string, label: string, min: unknown, max: unknown, home: unknown, speed: unknown, secondSpeed: unknown, state: AppState): string {
  return [`[${section}]`, `# ${label}.`, ...commonStepperLines(state, { includeEndstop: true, includeHoming: true, gearRatio: String(state.values.default_gear_ratio || '') }), `homing_speed: ${speed}`, `second_homing_speed: ${secondSpeed}`, `position_endstop: ${home}`, `position_min: ${min}`, `position_max: ${max}`].join('\n');
}

function deltaStepper(section: string, towerX: number, towerY: number, positionEndstop: unknown, state: AppState, includeHoming: boolean): string {
  const angle = ((Math.atan2(towerY, towerX) * 180) / Math.PI + 360) % 360;
  const v = state.values;
  return [`[${section}]`, '# Delta tower stepper.', ...commonStepperLines(state, { includeEndstop: true, includeHoming, gearRatio: String(v.default_gear_ratio || '') }), ...(includeHoming ? [`homing_speed: ${v.homing_speed_z}`, `second_homing_speed: ${fmt(num(v.homing_speed_z) / 2, 1)}`] : []), `position_endstop: ${positionEndstop}`, `arm_length: ${v.arm_length}`, `angle: ${fmt(angle)}`, `position_min: ${v.z_min}`, `# visual_tower_x: ${towerX}`, `# visual_tower_y: ${towerY}`].join('\n');
}

function genericCartesianSections(state: AppState): string {
  const carriages = state.carriages.map((c) => [`[carriage ${c.name.replace(/^carriage\s+/, '')}]`, `axis: ${c.axis}`, 'endstop_pin: CHANGE_ME', `position_endstop: ${c.endstop}`, `position_min: ${c.min}`, `position_max: ${c.max}`, `homing_speed: ${state.values.homing_speed_x}`, `homing_retract_dist: ${state.values.default_homing_retract_dist}`, ...(hasValue(state.values.default_homing_retract_speed) ? [`homing_retract_speed: ${state.values.default_homing_retract_speed}`] : []), `second_homing_speed: ${state.values.second_homing_speed}`, ...(hasValue(state.values.default_homing_positive_dir) ? [`homing_positive_dir: ${state.values.default_homing_positive_dir}`] : [])].join('\n'));
  const steppers = state.genericSteppers.map((s) => [`[${s.name}]`, '# Generic Cartesian stepper.', ...commonStepperLines(state, { includeEndstop: false, includeHoming: false, gearRatio: String(state.values.default_gear_ratio || '') }), `carriages: ${s.carriages}`, `# visual_equation: ${s.equation}`].join('\n'));
  return carriages.concat(steppers).join('\n\n');
}

interface StepperLineOptions {
  includeEndstop: boolean;
  includeHoming: boolean;
  omitRotationDistance?: boolean;
  gearRatio?: string;
}

function commonStepperLines(state: AppState, options: StepperLineOptions): string[] {
  const v = state.values;
  const lines = ['step_pin: CHANGE_ME', 'dir_pin: CHANGE_ME', 'enable_pin: CHANGE_ME'];
  if (!options.omitRotationDistance) lines.push(`rotation_distance: ${hasValue(v.default_rotation_distance) ? v.default_rotation_distance : 'CHANGE_ME'}`);
  lines.push(`microsteps: ${v.default_microsteps}`);
  if (hasValue(v.default_full_steps_per_rotation)) lines.push(`full_steps_per_rotation: ${v.default_full_steps_per_rotation}`);
  if (hasValue(options.gearRatio)) lines.push(`gear_ratio: ${options.gearRatio}`);
  if (hasValue(v.default_step_pulse_duration)) lines.push(`step_pulse_duration: ${v.default_step_pulse_duration}`);
  if (options.includeEndstop) lines.push('endstop_pin: CHANGE_ME');
  if (options.includeHoming) {
    lines.push(`homing_retract_dist: ${v.default_homing_retract_dist}`);
    if (hasValue(v.default_homing_retract_speed)) lines.push(`homing_retract_speed: ${v.default_homing_retract_speed}`);
    if (hasValue(v.default_homing_positive_dir)) lines.push(`homing_positive_dir: ${v.default_homing_positive_dir}`);
  }
  return lines;
}

function hasValue(value: unknown): boolean {
  return value !== '' && value !== null && value !== undefined;
}

function probeSections(state: AppState): string {
  const v = state.values;
  const lines: string[] = [];
  if (v.probe_deploy_pin) {
    lines.push('[output_pin probe_enable]', `pin: ${v.probe_deploy_pin}`, 'value: 0', '', '[gcode_macro Probe_Deploy]', 'gcode:', '  SET_PIN PIN=probe_enable VALUE=1', '', '[gcode_macro Probe_Stow]', 'gcode:', '  SET_PIN PIN=probe_enable VALUE=0', '');
  }
  lines.push('[probe]', `pin: ${v.probe_pin || 'CHANGE_ME'}`, `x_offset: ${v.probe_x_offset}`, `y_offset: ${v.probe_y_offset}`, `z_offset: ${v.probe_z_offset}`, `speed: ${v.probe_speed}`, `samples: ${Math.round(num(v.probe_samples) || 1)}`, `sample_retract_dist: ${v.probe_retract}`, `samples_tolerance: ${v.probe_tolerance}`, 'samples_tolerance_retries: 3');
  if (v.probe_deploy_pin) lines.push('activate_gcode:', '  Probe_Deploy', `  G4 P${Math.round(num(v.probe_deploy_delay))}`, 'deactivate_gcode:', '  Probe_Stow');
  return lines.join('\n');
}

function safeZHomeSection(state: AppState, kin: KinematicDefinition): string {
  const v = state.values;
  return ['[safe_z_home]', '# Nozzle moves here so the probe lands near the bed center.', `home_xy_position: ${fmt(safeHomeX(v, kin))}, ${fmt(safeHomeY(v, kin))}`, `speed: ${v.homing_speed_x}`, `z_hop: ${v.z_hop}`, 'z_hop_speed: 15'].join('\n');
}

function bedMeshSection(state: AppState): string {
  const v = state.values;
  const countX = Math.round(num(v.mesh_countx) || 2);
  const countY = Math.round(num(v.mesh_county) || 2);
  return ['[bed_mesh]', '# mesh_min/max are probe coordinates, not nozzle coordinates.', `speed: ${v.mesh_speed}`, `horizontal_move_z: ${v.mesh_hz}`, `mesh_min: ${v.mesh_xmin}, ${v.mesh_ymin}`, `mesh_max: ${v.mesh_xmax}, ${v.mesh_ymax}`, `probe_count: ${countX}, ${countY}`, 'mesh_pps: 2, 2', `algorithm: ${countX > 3 && countY > 3 ? 'bicubic' : 'lagrange'}`, 'fade_start: 1.0', 'fade_end: 10.0'].join('\n');
}

function screwsTiltSection(state: AppState): string {
  const v = state.values;
  const lines = ['[screws_tilt_adjust]', '# Screws are stored as physical machine coordinates; screwN values are nozzle positions after probe offsets.'];
  state.screws.forEach((s, index) => {
    const n = index + 1;
    lines.push(`# screw${n} physical: X${fmt(s.x)} Y${fmt(s.y)}`);
    lines.push(`screw${n}: ${fmt(s.x - num(v.probe_x_offset))}, ${fmt(s.y - num(v.probe_y_offset))}`);
    lines.push(`screw${n}_name: ${s.name}`);
  });
  lines.push('horizontal_move_z: 10', `speed: ${v.homing_speed_x}`, `screw_thread: ${v.screw_thread}`);
  return lines.join('\n');
}

function extruderSection(state: AppState): string {
  const v = state.values;
  const lines = [
    '[extruder]',
    '# Optional E stepper / hotend starter section.',
    'step_pin: CHANGE_ME',
    'dir_pin: CHANGE_ME',
    'enable_pin: CHANGE_ME',
    `microsteps: ${v.extruder_microsteps}`,
    `rotation_distance: ${hasValue(v.extruder_rotation_distance) ? v.extruder_rotation_distance : 'CHANGE_ME'}`
  ];
  if (hasValue(v.extruder_full_steps_per_rotation)) lines.push(`full_steps_per_rotation: ${v.extruder_full_steps_per_rotation}`);
  if (hasValue(v.extruder_gear_ratio)) lines.push(`gear_ratio: ${v.extruder_gear_ratio}`);
  lines.push(
    `nozzle_diameter: ${v.nozzle_diameter}`,
    `filament_diameter: ${v.filament_diameter}`,
    `max_extrude_only_distance: ${v.max_extrude_only_distance}`,
    'heater_pin: CHANGE_ME',
    'sensor_type: CHANGE_ME',
    'sensor_pin: CHANGE_ME',
    'control: pid',
    '# pid_Kp: CHANGE_ME',
    '# pid_Ki: CHANGE_ME',
    '# pid_Kd: CHANGE_ME',
    `min_temp: ${v.extruder_min_temp}`,
    `max_temp: ${v.extruder_max_temp}`
  );
  return lines.join('\n');
}

function summarySection(kin: KinematicDefinition, state: AppState): string {
  const motors = getMotorReadout(state).map((row) => `#   ${row.label}: ${row.value}`).join('\n');
  return ['# Positioning summary', `#   Kinematics: ${kin.id}`, `#   Toolhead: X${fmt(state.toolhead.x)} Y${fmt(state.toolhead.y)} Z${fmt(state.toolhead.z)}`, motors].join('\n');
}
